version: '3'

services:
  backend:
    build: ./backend
    networks:
      - incloudg3       
    container_name: backend
    env_file:
      - .env
    ports:
      - "4040:3000"
    depends_on:
      - database

  frontend:
    build: ./front
    networks:
      - incloudg3     
    container_name: frontend
    ports:
      - "8090:4200"           
    depends_on:
      - backend

  database:
    image: mysql:8
    networks:
      - incloudg3 
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: cps123
      MYSQL_DATABASE: incloudDB
      MYSQL_USER: incloud_user_admin
      MYSQL_PASSWORD: cps123
    ports:
      - "3351:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d

networks:
  incloudg3:
    driver: bridge

volumes:
  db_data:
